"""Regenerate the self-hosted web fonts from vinext's font cache.

Why this exists: `next/font` cannot be used in this project. vinext downloads
the woff2 files correctly into `frontend/.vinext/fonts/`, but writes an absolute
filesystem path into the generated @font-face --

    src: url(C:/Users/.../frontend/.vinext/fonts/.../bricolage-*.woff2)

-- which the browser refuses to fetch as a file:// resource. Every next/font
face therefore lands in `error` state and silently falls back, which is why the
whole product rendered in Geist despite pen-design.css naming three other
families.

This copies the same woff2 files into `frontend/public/fonts/` and rewrites the
declarations to real `/fonts/...` URLs, so the families resolve by their real
names. Self-hosted rather than pulled from the Google Fonts CDN, because the
product's own promise is that a screening runs locally.

Run after adding a family (add it to FAMILIES, run a build so vinext fetches it,
then run this):

    cd frontend && npm run build
    python tools/fonts/sync_fonts.py
"""

from __future__ import annotations

import pathlib
import re
import shutil
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
CACHE = ROOT / "frontend" / ".vinext" / "fonts"
PUBLIC = ROOT / "frontend" / "public" / "fonts"
OUT = ROOT / "frontend" / "app" / "styles" / "fonts.css"

# Directory slug -> the family name the stylesheets actually write.
FAMILIES = {
    "bricolage-grotesque": "Bricolage Grotesque",
    "instrument-sans": "Instrument Sans",
    "fragment-mono": "Fragment Mono",
}

# The document is English; shipping Cyrillic and Vietnamese subsets would be
# dead weight in the bundle.
SUBSETS = ("latin", "latin-ext")

HEADER = """/* Self-hosted display, body and label faces.

   These are the three families styles/pen-design.css has always named. They
   cannot come through next/font here: vinext emits an absolute filesystem path
   into the generated @font-face (src: url(C:/Users/...)), which the browser
   refuses as a file:// resource, so every next/font face lands in `error` state
   and silently falls back. Serving the same woff2 files from /public sidesteps
   that pipeline and keeps them local -- no CDN request at page load.

   Generated by tools/fonts/sync_fonts.py -- edit that, not this. */

"""


def main() -> int:
    if not CACHE.exists():
        print(f"no font cache at {CACHE}; run `npm run build` in frontend/ first", file=sys.stderr)
        return 1

    PUBLIC.mkdir(parents=True, exist_ok=True)
    blocks: list[str] = []
    seen: set[str] = set()

    for directory in sorted(CACHE.iterdir()):
        slug = re.sub(r"-[0-9a-f]{12}$", "", directory.name)
        family = FAMILIES.get(slug)
        if not family:
            continue
        seen.add(slug)
        css = (directory / "style.css").read_text(encoding="utf-8")
        for match in re.finditer(r"/\*\s*([\w-]+)\s*\*/\s*(@font-face\s*\{.*?\})", css, re.S):
            subset, face = match.group(1), match.group(2)
            if subset not in SUBSETS:
                continue
            filename = re.search(r"url\([^)]*/([^/)]+\.woff2)\)", face).group(1)
            source = directory / filename
            if source.exists():
                shutil.copy2(source, PUBLIC / filename)
            face = re.sub(r"url\([^)]+\)", f"url(/fonts/{filename})", face)
            # next/font rewrites the family to a hashed name; restore the real
            # one so the stylesheets resolve it directly.
            face = re.sub(r"font-family:\s*'[^']*'", f"font-family: '{family}'", face)
            blocks.append(f"/* {family} — {subset} */\n{face}")

    missing = sorted(set(FAMILIES) - seen)
    if missing:
        print(f"warning: no cached files for {missing}; build first", file=sys.stderr)

    OUT.write_text(HEADER + "\n\n".join(blocks) + "\n", encoding="utf-8")
    print(f"wrote {len(blocks)} @font-face blocks -> {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
