from __future__ import annotations

import fitz


# The first-run sample. A new reviewer who lands on an empty dashboard has no
# way to learn what a verdict looks like without uploading a real document, so
# the app can generate this one instead. It is drawn here rather than shipped as
# a file so it can never be mistaken for a genuine record: every copy says
# SAMPLE, and the issuing body is fictional.
SAMPLE_FILENAME = "sample-certificate.pdf"

# Kept to fast, text-layer checks. The sample exists to show the shape of a
# result quickly; the heavy capture detectors would make first run feel slow.
SAMPLE_ANALYZERS = ["metadata", "font_analysis", "readability", "qr_presence"]

_FIELDS = [
    ("Certificate number", "SMP/2026/000417"),
    ("Issued to", "A. Placeholder"),
    ("Programme", "Demonstration of document screening"),
    ("Date of issue", "14 July 2026"),
    ("Issuing body", "Parakh Sample Authority (fictional)"),
]


def build_sample_document() -> bytes:
    """Render the synthetic sample certificate as PDF bytes."""

    document = fitz.open()
    try:
        page = document.new_page(width=595, height=842)  # A4 at 72 dpi

        page.draw_rect(fitz.Rect(40, 40, 555, 802), color=(0.55, 0.55, 0.62), width=1)
        page.insert_text((56, 86), "PARAKH SAMPLE AUTHORITY", fontname="Helvetica-Bold", fontsize=13)
        page.insert_text((56, 104), "Synthetic document generated for demonstration", fontsize=9,
                         color=(0.35, 0.35, 0.42))

        page.insert_text((56, 168), "Certificate of Completion", fontname="Times-Bold", fontsize=26)
        page.insert_text((56, 196), "This document is a sample. It certifies nothing.", fontsize=11,
                         color=(0.3, 0.3, 0.36))

        y = 260
        for label, value in _FIELDS:
            page.insert_text((56, y), label.upper(), fontsize=8, color=(0.42, 0.42, 0.5))
            page.insert_text((56, y + 17), value, fontname="Helvetica", fontsize=12)
            page.draw_line(fitz.Point(56, y + 27), fitz.Point(539, y + 27), color=(0.86, 0.86, 0.9), width=0.6)
            y += 58

        # A drawn signature stroke, so the signature check has something real to
        # look at rather than an empty page.
        page.draw_bezier(
            fitz.Point(80, 640), fitz.Point(130, 600), fitz.Point(180, 680), fitz.Point(240, 628),
            color=(0.09, 0.09, 0.16), width=1.6,
        )
        page.draw_line(fitz.Point(72, 660), fitz.Point(260, 660), color=(0.6, 0.6, 0.68), width=0.6)
        page.insert_text((72, 676), "Authorised signatory (sample)", fontsize=8, color=(0.42, 0.42, 0.5))

        page.insert_text((56, 770), "SAMPLE — NOT A GENUINE CERTIFICATE", fontname="Helvetica-Bold",
                         fontsize=11, color=(0.72, 0.24, 0.35))
        page.insert_text((56, 786), "Generated by Parakh so a first-time reviewer can see a real verdict.",
                         fontsize=8, color=(0.42, 0.42, 0.5))

        # A large diagonal watermark, so a printed copy is unmistakable too.
        watermark = fitz.TextWriter(page.rect)
        watermark.append(fitz.Point(140, 520), "SAMPLE", fontsize=90,
                         font=fitz.Font("Helvetica-Bold"))
        watermark.write_text(page, color=(0.85, 0.85, 0.9), morph=(fitz.Point(140, 520),
                                                                  fitz.Matrix(30)))

        document.set_metadata({
            "title": "Parakh sample certificate",
            "author": "Parakh Sample Authority (fictional)",
            "producer": "Parakh sample generator",
            "subject": "Synthetic document for first-run demonstration",
        })
        return document.tobytes(garbage=4, deflate=True)
    finally:
        document.close()
